# Generated by Django 6.0.5 on 2026-06-05 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_set_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='sets',
        ),
        migrations.AddField(
            model_name='set',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='fitness.workout'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
