# Generated by Django 6.0.5 on 2026-06-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_remove_workout_sets_set_workout_workout_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='duration',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
