# Generated by Django 6.0.5 on 2026-06-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_set_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='workout',
        ),
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.ManyToManyField(related_name='exercises', to='fitness.set'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='workouts',
            field=models.ManyToManyField(related_name='exercises', to='fitness.workout'),
        ),
    ]
