# Generated by Django 6.0.5 on 2026-06-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_remove_set_workout_exercise_sets_exercise_workouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
