# Generated by Django 6.0.5 on 2026-06-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_set_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='workouts',
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='workouts', to='fitness.exercise'),
        ),
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=models.ManyToManyField(blank=True, related_name='workouts', to='fitness.set'),
        ),
    ]
