# Generated by Django 6.0.5 on 2026-06-18 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_remove_exercise_sets_remove_exercise_workouts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='set',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='sets',
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='fitness.workout')),
            ],
        ),
        migrations.AddField(
            model_name='set',
            name='workout_exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='fitness.workoutexercise'),
            preserve_default=False,
        ),
    ]
