# Generated by Django 6.0.5 on 2026-06-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0010_workout_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.CharField(default='00:00:00', max_length=8),
        ),
    ]
