# Generated by Django 6.0.5 on 2026-06-27 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0013_workout_is_template_trainingplan_workout_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='parent_workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness.workout'),
        ),
    ]
